# Конфигурационный файл для проекта OPC

database:
  path: "server_opc.db"

backtester:
  weights:
    basis: 0.4
    history: 0.4
    news: 0.2
  decision_thresholds:
    strong_buy: 0.8
    buy: 0.7
    sell: 0.3
    strong_sell: 0.2

prediction_layer:
  window_size: 5

block_detector:
  threshold: 1.5
  window: 50

block_analyzer:
  market_regime_thresholds:
    trending:
      mean_error: [0.0, 0.8]
      std_error: [0.0, 0.4]
      trend: [-0.1, 0.1]
    volatile:
      mean_error: [1.0, 3.0]
      std_error: [0.5, 2.0]
      trend: [-0.2, 0.2]
    stable:
      mean_error: [0.0, 0.5]
      std_error: [0.0, 0.3]
      trend: [-0.05, 0.05]
    transition:
      mean_error: [0.5, 1.5]
      std_error: [0.3, 0.8]
      trend: [-0.15, 0.15]

api:
  bybit_url: "https://api.bybit.com"

data:
  timeframes:
    spot: "1m"
    futures: "1m"
    iv: "1m"
    trend_signals: "15m"